use_frameworks!
platform :ios, '8.0'
target 'LYShowManager_Example' do
  pod 'LYShowManager', :path => '../'

  target 'LYShowManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
